tasks:
  - name: cdk
    before: |
      npm i -g aws-cdk
  - name: terraform
    before: |
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      sudo apt-get update && sudo apt-get install terraform
  # random utilities
  - name: utils 
    before: |
      sudo apt-get install tree
  # https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.4
  # https://docs.aws.amazon.com/powershell/latest/userguide/pstools-getting-set-up-linux-mac.html
  # https://docs.aws.amazon.com/powershell/latest/reference/
  #- name: powershell
  #  before: |
  #    ./bin/powershell_cli_install.sh
  # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      ./bin/aws_cli_install.sh