tasks:
  - name: aws cli
    before: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      mkdir -p ~/.aws
      cat > ~/.aws/credentials <<EOF
      [default]
      aws_access_key_id = example
      aws_secret_access_key = example
      EOF
      cat > ~/.aws/config <<EOF
      [default]
      region = us-east-1
      output = json
      EOF
    command: |
      cd AWS-Examples
      echo "Workspace started inside AWS-Examples folder"

ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

workspaceLocation: AWS-Examples
