tasks:
  - name: cdk
    before: |
      npm install -g aws-cdk

  - name: terraform
    before: |
      ./bin/terraform_cli_install.sh

  - name: utils
    before: |
      sudo apt-get update
      sudo apt-get install -y tree

  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      ./bin/aws_cli_install.sh
